# ref: https://github.com/rubocop/rubocop-rails/blob/v2.19.1/config/default.yml
# Disable Rubocop Rails

Rails/DefaultScope:
  Description: 'Avoid use of `default_scope`.'
  StyleGuide: 'https://rails.rubystyle.guide#avoid-default-scope'
  Enabled: false
  VersionAdded: '2.7'

Rails/EnvironmentVariableAccess:
  Description: 'Do not access `ENV` directly after initialization.'
  # TODO: Set to `pending` status in RuboCop Rails 2 series when migration doc will be written.
  Enabled: false
  VersionAdded: '2.10'
  VersionChanged: '2.11'
  Include:
    - app/**/*.rb
    - lib/**/*.rb
  Exclude:
    - lib/**/*.rake
  AllowReads: false
  AllowWrites: false

Rails/OrderById:
  Description: >-
    Do not use the `id` column for ordering.
    Use a timestamp column to order chronologically.
  StyleGuide: 'https://rails.rubystyle.guide/#order-by-id'
  Enabled: false
  VersionAdded: '2.8'

Rails/PluckId:
  Description: 'Use `ids` instead of `pluck(:id)` or `pluck(primary_key)`.'
  StyleGuide: 'https://rails.rubystyle.guide/#ids'
  Enabled: false
  Safe: false
  VersionAdded: '2.7'

Rails/RequireDependency:
  Description: 'Do not use `require_dependency` when running in Zeitwerk mode. `require_dependency` is for autoloading in classic mode.'
  Reference: 'https://guides.rubyonrails.org/autoloading_and_reloading_constants.html'
  Enabled: false
  VersionAdded: '2.10'

Rails/ReversibleMigrationMethodDefinition:
  Description: 'Checks whether the migration implements either a `change` method or both an `up` and a `down` method.'
  Enabled: false
  VersionAdded: '2.10'
  VersionChanged: '2.13'
  Include:
    - db/**/*.rb

Rails/SaveBang:
  Description: 'Identifies possible cases where Active Record save! or related should be used.'
  StyleGuide: 'https://rails.rubystyle.guide#save-bang'
  Enabled: false
  VersionAdded: '0.42'
  VersionChanged: '0.59'
  AllowImplicitReturn: true
  AllowedReceivers: []
  SafeAutoCorrect: false

Rails/SchemaComment:
  Description: >-
    Enforces the use of the `comment` option when adding a new table or column
    to the database during a migration.
  Enabled: false
  VersionAdded: '2.13'

Rails/TableNameAssignment:
  Description: >-
    Do not use `self.table_name =`. Use Inflections or `table_name_prefix` instead.
  StyleGuide: 'https://rails.rubystyle.guide/#keep-ar-defaults'
  Enabled: false
  VersionAdded: '2.14'
  Include:
    - app/models/**/*.rb
