models:
  token:
    ttl: 28800 # 8 hours
  transaction:
    amount:
      numericality:
        greater_than: 0
  user:
    email:
      length:
        max: 255
    password:
      length:
        in: !ruby/range 6..128
